import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for DesiRig.com",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-12">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Effective Date: March 9, 2026 | Last Modified: March 9, 2026
      </p>

      <div className="mt-8 space-y-6 text-xs leading-relaxed text-muted-foreground [&_h2]:text-sm [&_h2]:font-bold [&_h2]:text-foreground [&_h2]:uppercase [&_h2]:tracking-wide [&_h2]:mt-8 [&_h2]:mb-2">

        <p>
          PLEASE READ THESE TERMS OF SERVICE (&quot;TERMS&quot;, &quot;AGREEMENT&quot;) CAREFULLY BEFORE
          ACCESSING OR USING THE WEBSITE LOCATED AT DESIRIG.COM (THE &quot;SERVICE&quot;, &quot;PLATFORM&quot;,
          OR &quot;SITE&quot;), OPERATED BY DESIRIG (&quot;COMPANY&quot;, &quot;WE&quot;, &quot;US&quot;, OR &quot;OUR&quot;). YOUR ACCESS
          TO AND USE OF THE SERVICE IS CONDITIONED ON YOUR ACCEPTANCE OF AND COMPLIANCE WITH
          THESE TERMS. BY ACCESSING OR USING THE SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS.
          IF YOU DISAGREE WITH ANY PART OF THE TERMS, YOU MAY NOT ACCESS THE SERVICE.
        </p>

        <h2>1. DEFINITIONS AND INTERPRETATION</h2>
        <p>
          1.1 &quot;Aggregate Data&quot; means data compiled from publicly accessible sources, including
          but not limited to government databases, public registries, regulatory filings, and
          publicly available business directories, which has been organized, indexed, and
          presented through the Service.
        </p>
        <p>
          1.2 &quot;Content&quot; means all text, data, information, graphics, images, or other materials
          displayed on, generated by, or made available through the Service, including without
          limitation business listings, safety records, ratings, reviews, and user-generated content.
        </p>
        <p>
          1.3 &quot;Government Data&quot; means information sourced from publicly available government
          databases, regulatory agencies, open data portals, and public records maintained by
          federal, provincial, territorial, state, or municipal authorities in Canada, the
          United States, or other jurisdictions.
        </p>
        <p>
          1.4 &quot;User&quot;, &quot;You&quot;, or &quot;Your&quot; refers to any individual or entity that accesses,
          browses, or otherwise uses the Service, whether or not such individual or entity has
          created an account.
        </p>
        <p>
          1.5 &quot;Listed Entity&quot; means any business, organization, carrier, or individual whose
          information appears as a listing on the Service.
        </p>

        <h2>2. NATURE OF THE SERVICE</h2>
        <p>
          2.1 The Service is an online directory and information aggregation platform that compiles
          publicly available business information and government records for informational purposes
          only. The Service does not create, verify, endorse, or guarantee the accuracy of any
          Content unless explicitly designated as &quot;DesiRig Verified&quot; through a separate
          verification process.
        </p>
        <p>
          2.2 THE SERVICE IS NOT AND SHALL NOT BE CONSTRUED AS PROVIDING LEGAL, FINANCIAL,
          INSURANCE, MEDICAL, SAFETY, EMPLOYMENT, OR ANY OTHER FORM OF PROFESSIONAL ADVICE.
          THE COMPANY IS NOT A LICENSED PROFESSIONAL IN ANY JURISDICTION FOR ANY PURPOSE AND
          MAKES NO REPRESENTATIONS REGARDING THE SUITABILITY, RELIABILITY, OR APPROPRIATENESS
          OF ANY LISTED ENTITY FOR ANY PARTICULAR PURPOSE.
        </p>

        <h2>3. DATA SOURCES AND ACCURACY DISCLAIMER</h2>
        <p>
          3.1 Business listings and associated information displayed on the Service are derived
          from publicly accessible data sources, including but not limited to public government
          databases, open data portals, regulatory filings, publicly available directories,
          and user-submitted information. The Company utilizes proprietary methods to aggregate,
          organize, and present such data.
        </p>
        <p>
          3.2 THE COMPANY MAKES NO WARRANTY, REPRESENTATION, OR GUARANTEE, WHETHER EXPRESS,
          IMPLIED, STATUTORY, OR OTHERWISE, REGARDING THE ACCURACY, COMPLETENESS, TIMELINESS,
          RELIABILITY, SUITABILITY, OR AVAILABILITY OF ANY CONTENT, DATA, OR INFORMATION
          PRESENTED THROUGH THE SERVICE. ALL CONTENT IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS
          AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND.
        </p>
        <p>
          3.3 Information displayed on the Service, including without limitation business contact
          details, operational status, safety records, fleet information, and regulatory compliance
          data, may be outdated, incomplete, or inaccurate due to the inherent limitations of
          third-party data sources, transmission delays, processing intervals, or changes that
          have not yet been reflected in the underlying databases from which the Service draws
          its Content.
        </p>
        <p>
          3.4 Users are solely responsible for independently verifying any information obtained
          through the Service before making any decisions based thereon, including but not limited
          to employment decisions, business engagements, safety assessments, insurance evaluations,
          carrier selection, or any other material decisions.
        </p>

        <h2>4. SAFETY AND REGULATORY DATA &mdash; SPECIFIC DISCLAIMERS</h2>
        <p>
          4.1 Carrier safety records, regulatory identifiers, safety ratings, inspection records,
          fleet information, and other regulatory data displayed on the Service are sourced from
          publicly available government databases and regulatory agencies.
        </p>
        <p>
          4.2 Where technically feasible, the Service may retrieve regulatory data in real-time
          from public government APIs. However, the Company cannot guarantee that real-time
          retrieval will always be available, and the Service may display cached data of
          indeterminate age in the event of source unavailability, network issues, rate limiting,
          or any other technical impediment.
        </p>
        <p>
          4.3 Regulatory and safety data is provided for general informational purposes only and
          SHALL NOT be relied upon as the sole or primary basis for any safety assessment,
          employment decision, carrier selection, insurance underwriting, or regulatory compliance
          determination. For authoritative and official records, users must consult the
          appropriate regulatory authority in their jurisdiction directly.
        </p>

        <h2>5. AUTOMATED CLASSIFICATION AND COMMUNITY DESIGNATIONS</h2>
        <p>
          5.1 The Service employs automated algorithmic methods, including without limitation
          pattern matching, natural language processing heuristics, and proprietary classification
          models, to apply community-related designations (such as &quot;Desi Owned&quot;) to certain
          Listed Entities. These classifications are probabilistic approximations based on
          publicly available information and may contain both false positives (entities
          incorrectly classified) and false negatives (entities not classified despite qualifying).
        </p>
        <p>
          5.2 The Company makes no representation that any automated classification is accurate,
          complete, or appropriate. Community designations do not constitute statements of fact,
          endorsements, or certifications by the Company. Listed Entities may request addition,
          modification, or removal of such designations at any time by contacting the Company
          at rig@desirig.com.
        </p>

        <h2>6. LISTED ENTITY RIGHTS AND OBLIGATIONS</h2>
        <p>
          6.1 Listed Entities acknowledge that their information has been compiled from publicly
          available sources and that display of such information does not constitute appropriation,
          misuse, or violation of any proprietary right. Nothing in the Service creates any
          agency, partnership, joint venture, or employment relationship between the Company
          and any Listed Entity.
        </p>
        <p>
          6.2 Listed Entities may request: (a) correction of inaccurate information; (b) removal
          of their listing from the Service; (c) addition, modification, or removal of community
          designations; or (d) any other reasonable modification, by submitting a written request
          to rig@desirig.com. The Company shall use commercially reasonable efforts to process
          such requests within seven (7) business days of receipt of a verifiable request.
        </p>
        <p>
          6.3 The Company reserves the right to retain aggregated, anonymized, or statistical
          data derived from Listed Entity information even after removal of a specific listing,
          provided such retained data does not identify or permit identification of the Listed
          Entity.
        </p>

        <h2>7. PROHIBITED USES</h2>
        <p>
          7.1 You shall not, directly or indirectly: (a) systematically retrieve, scrape, harvest,
          spider, crawl, or use any automated means to access, collect, copy, or download data
          from the Service; (b) use the Service or any Content obtained therefrom for unsolicited
          commercial communications, spam, or bulk messaging of any kind; (c) attempt to
          circumvent, disable, or interfere with any security, access control, rate limiting,
          or other protective features of the Service; (d) reverse engineer, decompile, or
          disassemble any portion of the Service; (e) use the Service in any manner that violates
          applicable federal, provincial, state, or local laws or regulations, including without
          limitation Canada&apos;s Anti-Spam Legislation (CASL), the Personal Information Protection
          and Electronic Documents Act (PIPEDA), or equivalent legislation in any jurisdiction;
          (f) misrepresent your identity, affiliation, or authority with respect to any Listed
          Entity; or (g) use the Service to compete directly with the Service or to create a
          substantially similar product or service.
        </p>

        <h2>8. INTELLECTUAL PROPERTY</h2>
        <p>
          8.1 The compilation, arrangement, selection, coordination, and presentation of Content
          on the Service, together with the Service&apos;s software, algorithms, data models, design,
          logos, trademarks, and other proprietary elements, are the exclusive property of the
          Company and are protected by Canadian copyright law, international copyright treaties,
          and other applicable intellectual property laws. The Company&apos;s proprietary data
          aggregation, classification, and enrichment methodologies constitute trade secrets
          of the Company.
        </p>
        <p>
          8.2 Government Data incorporated into the Service remains subject to the terms of
          its original license, including without limitation applicable open government licenses,
          public domain designations, and other open data terms of use.
        </p>

        <h2>9. LIMITATION OF LIABILITY</h2>
        <p>
          9.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY,
          ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE
          DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, DATA,
          BUSINESS OPPORTUNITIES, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION
          WITH: (A) YOUR USE OF OR INABILITY TO USE THE SERVICE; (B) ANY CONTENT, DATA, OR
          INFORMATION OBTAINED FROM OR THROUGH THE SERVICE; (C) ANY CONDUCT OR CONTENT OF
          ANY THIRD PARTY ON THE SERVICE; (D) UNAUTHORIZED ACCESS TO, ALTERATION OF, OR
          DISCLOSURE OF YOUR DATA; OR (E) ANY OTHER MATTER RELATING TO THE SERVICE, WHETHER
          BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY
          OTHER LEGAL THEORY, REGARDLESS OF WHETHER THE COMPANY HAS BEEN INFORMED OF THE
          POSSIBILITY OF SUCH DAMAGE.
        </p>
        <p>
          9.2 IN NO EVENT SHALL THE COMPANY&apos;S TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING
          OUT OF OR RELATING TO THESE TERMS OR THE SERVICE EXCEED THE GREATER OF: (A) THE
          AMOUNT YOU HAVE PAID TO THE COMPANY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM;
          OR (B) ONE HUNDRED CANADIAN DOLLARS (CAD $100.00).
        </p>

        <h2>10. INDEMNIFICATION</h2>
        <p>
          10.1 You agree to indemnify, defend, and hold harmless the Company and its officers,
          directors, employees, agents, and affiliates from and against any and all claims,
          liabilities, damages, losses, costs, and expenses (including reasonable legal fees
          and disbursements) arising out of or in connection with: (a) your use of the Service;
          (b) your violation of these Terms; (c) your violation of any third-party rights,
          including without limitation intellectual property rights, privacy rights, or publicity
          rights; or (d) any content you submit to or through the Service.
        </p>

        <h2>11. DISPUTE RESOLUTION AND GOVERNING LAW</h2>
        <p>
          11.1 These Terms and any dispute arising out of or relating to these Terms or the
          Service shall be governed by and construed in accordance with the laws of the Province
          of Ontario and the federal laws of Canada applicable therein, without regard to
          conflict of law principles.
        </p>
        <p>
          11.2 Any dispute, controversy, or claim arising out of or relating to these Terms,
          including the validity, invalidity, breach, or termination thereof, shall first be
          subject to good-faith negotiation between the parties for a period of not less than
          thirty (30) days. If the dispute cannot be resolved through negotiation, it shall
          be submitted to the exclusive jurisdiction of the courts of the Province of Ontario,
          Canada.
        </p>
        <p>
          11.3 TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT ANY CLAIM OR CAUSE
          OF ACTION ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS MUST BE FILED
          WITHIN ONE (1) YEAR AFTER SUCH CLAIM OR CAUSE OF ACTION AROSE, OR BE FOREVER BARRED.
        </p>

        <h2>12. MODIFICATION AND TERMINATION</h2>
        <p>
          12.1 The Company reserves the right to modify, suspend, or discontinue the Service
          (or any part thereof) at any time, with or without notice, and without liability
          to you or any third party.
        </p>
        <p>
          12.2 The Company reserves the right to modify these Terms at any time by posting
          the revised Terms on the Service. Your continued use of the Service following the
          posting of revised Terms constitutes your acceptance of such changes.
        </p>

        <h2>13. SEVERABILITY AND WAIVER</h2>
        <p>
          13.1 If any provision of these Terms is found to be unenforceable or invalid under
          applicable law, such unenforceability or invalidity shall not render these Terms
          unenforceable or invalid as a whole. Such provisions shall be modified to the minimum
          extent necessary to make them enforceable, or if modification is not possible, shall
          be severed without affecting the remaining provisions herein.
        </p>
        <p>
          13.2 No waiver of any term or condition set forth in these Terms shall be deemed a
          further or continuing waiver of such term or condition or a waiver of any other term
          or condition, and any failure of the Company to assert a right or provision under
          these Terms shall not constitute a waiver of such right or provision.
        </p>

        <h2>14. ENTIRE AGREEMENT</h2>
        <p>
          14.1 These Terms, together with the Privacy Policy and any other legal notices
          published by the Company on the Service, constitute the entire agreement between
          you and the Company regarding the Service and supersede all prior and contemporaneous
          understandings, agreements, representations, and warranties, both written and oral,
          regarding the Service.
        </p>

        <h2>15. CONTACT INFORMATION</h2>
        <p>
          For questions, concerns, or requests regarding these Terms of Service, contact
          the Company at:{" "}
          <a href="mailto:rig@desirig.com" className="text-orange-600 hover:underline">
            rig@desirig.com
          </a>
        </p>
      </div>
    </div>
  );
}
